DATABASE_HOSTNAME: "localhost"
DATABASE_NAME: "api_base_db"
DATABASE_USERNAME: "root"
DATABASE_PASSWORD: "qweqwe123"
REDIS_HOSTNAME: "redis"
DATABASE_PORT: "3306"

ACCEESS_TOKEN_INSTAGRAM: "2240568780.9c3f4f2.ae0f588101b7496299874993e776ac68"
