default: &default
  adapter: mysql2
  reconnect: true
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_bin
  pool: <%= ENV["MYSQL_POOL"] %>
  host: <%= ENV["DATABASE_HOSTNAME"] %>
  username: <%= ENV["DATABASE_USERNAME"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  port: <%= ENV["DATABASE_PORT"] %>
  redis:
    host: redis://<%= ENV["REDIS_HOSTNAME"] %>:6379
    options:
      :namespace: <%= ENV["DATABASE_NAME"] %>

development:
  database: <%= ENV["DATABASE_NAME"] %>
  <<: *default

test:
  database: todo_api_test
  <<: *default

staging:
  database: <%= ENV["DATABASE_NAME"] %>
  <<: *default

production:
  database: <%= ENV["DATABASE_NAME"] %>
  <<: *default
